### ISSUE TITLE
无法生成正确的nfo文件

### ISSUE THREAD

**Issue by xinyo** [JavScraper/Emby.Plugins.JavScraper#1]
运行程序后
女优头像.nfo 文件内只包含内容为:
"女优头像.nfo"
![image](https://user-images.githubusercontent.com/5722044/74100421-d20b2980-4b82-11ea-83c4-3af5b69a0ede.png)
![image](https://user-images.githubusercontent.com/5722044/74100427-e8b18080-4b82-11ea-8599-e88b10e309df.png)
![image](https://user-images.githubusercontent.com/5722044/74100436-f6ff9c80-4b82-11ea-8839-da7814053131.png)

**Comment by JavScraper** [comment]
手抖把文件名填到内容中去了。。。马上更新。

**Comment by JavScraper** [comment]
@xinyo 可以了，重新下载。谢谢反馈。
