### ISSUE TITLE
请问刮削后的数据存在哪里了？

### ISSUE THREAD

**Issue by Leonuoa7** [JavScraper/Emby.Plugins.JavScraper#105]
### 问题描述

刮削后在影片目录下在找不到nfo文件以及封面图数据，然后我在/config/data目录下发现了JavScraper.db文件，但是它无法当作SQLite数据库打开

### 问题必要性

1. 进行数据备份和迁移，emby自带的备份插件是收费的
2. 批量修改nfo元数据，刮削后的数据我可能要批量添加tag等

**Comment by joast888** [comment]
媒体库设置，编辑，勾选nfo储存方式

**Comment by Leonuoa7** [comment]
> 
> 
> 媒体库设置，编辑，勾选nfo储存方式

创建媒体库的时候已经勾选了这个。刮削后emby里可以正常显示，说明元数据已经刮到了。但是影片所在文件夹里找不到nfo文件，而且poster文件也不在这里（我也勾选了“图片文件存在媒体所在文件夹”）。不知是哪个配置流程出了问题

**Comment by Leonuoa7** [comment]
issue #87 解释了刮削数据存放的问题，是由于文件权限引起的，我把整个媒体文件夹权限改成777了，然后就有nfo和图片了。

现在的问题是777权限谁都可以rwx，怎么设置才能只让emby可以rwx。我的使用环境是在CentOS用Docker安装的emby，然后把/config和/media文件做了映射，修改权限之前在CentOS里和在emby的容器里查看到这两个文件夹权限都是755、所属用户root、所属用户组root。
