### ISSUE TITLE
国产AV如麻豆传媒，有什么搜刮方法吗

### ISSUE THREAD

**Issue by ChaoW95** [JavScraper/Emby.Plugins.JavScraper#109]
我这里有视频，如何搜刮图片，标题和演员呢？

现在麻豆视频已经很多了，各位有没有什么好的整理办法？

**Comment by 277383761** [comment]
看了你的标题,我也下载了这个合集,求刮削方案

**Comment by xh542428798** [comment]
刮取成功了吗，我想要视频

**Comment by 277383761** [comment]
没成功,这个emby官方没有收录的,无法刮削




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hui ***@***.***&gt;; 
发送时间: 2021年5月3日(星期一) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JavScraper/Emby.Plugins.JavScraper] 国产AV如麻豆传媒，有什么搜刮方法吗 (#109)





 
刮取成功了吗，我想要视频
