### ISSUE TITLE
最新的v1.2021.0203.2330版本在jellyfin失效

### ISSUE THREAD

**Issue by elizhyu** [JavScraper/Emby.Plugins.JavScraper#111]
再更新至今天刚发布的`v1.2021.0203.2330`版本后，虽然插件仍可被识别，但javscraper消失在了各个库的刮削器列表中，且无法进行刮削功能。在将版本roll back回前一版本`v1.2020.1229.2200`后，所有功能回复正常，且又可以被识别在刮削器列表中。

`本人的jellyfin版本为10.6.4.`

**Comment by kid0613** [comment]
一樣 ,並且女優頭像刮削選項消失

**Comment by JavScraper** [comment]
已经发布新版本，麻烦测试下，谢谢。

**Comment by elizhyu** [comment]
在最新的`v1.2021.0205.2100`版本后，jellyfin支持已被修复

> 个人测试所有功能都可正常运行在jellyfin版本10.6.4

**Comment by kid0613** [comment]
FC2刮削？

**Comment by elizhyu** [comment]
> FC2刮削？

之前的描述可能有些许遗漏，FC2仍不可用。
