### ISSUE TITLE
代理服务器是不是炸了

### ISSUE THREAD

**Issue by bzvroo** [JavScraper/Emby.Plugins.JavScraper#116]
Please check back later
Error 1027
 This website has been temporarily rate limited

You cannot access this site because the owner has reached their plan limits. Check back later once traffic has gone down.

If you are owner of this website, prevent this from happening again by upgrading your plan on the Cloudflare Workers dashboard.

Learn more about this issue →

**Comment by JavScraper** [comment]
是的，经常超限额，目前无解。建议根据教程自己搭建。
