### ISSUE TITLE
Jav123 更新了 Scraper的 element text

### ISSUE THREAD

**Issue by simonlkch** [JavScraper/Emby.Plugins.JavScraper#119]
番号 -> 品番
女优 -> 出演者
标签 -> ジャンル
片商 -> メーカー

发行日期 -> 配信開始日
播放时长 -> 収録時間

我改了source code 後 可正常使用

**Comment by redrui666** [comment]
这个怎么修改呢？在哪里 求大神执教

**Comment by redrui666** [comment]
@simonlkch

**Comment by simonlkch** [comment]
@redrui666  在jav123.cs 中修改 以上的字眼, 之後build dll出來, 重新放到emby或jellybin中
只是jav123 中的字眼轉了 所以出現找不到num 和 actor

**Comment by PHCSJC** [comment]
@simonlkch 不会编译，可以上传一个吗？谢谢！

**Comment by simonlkch** [comment]
@PHCSJC 等作者更新吧

**Comment by xjasonlyu** [comment]
@PHCSJC 等作者更新之前我临时修复了一下凑合着用🌚，本地测试了一下是没问题了。

https://github.com/xjasonlyu/Emby.Plugins.JavScraper/releases/tag/v1.2021.0217.1440

**Comment by xjasonlyu** [comment]
@redrui666

**Comment by redrui666** [comment]
谢谢 我试试看

**Comment by redrui666** [comment]
@xjasonlyu 谢谢大佬 实测可用！

**Comment by simonlkch** [comment]
作者已更新
