### ISSUE TITLE
有图片刷不出来的么？

### ISSUE THREAD

**Issue by kasimok** [JavScraper/Emby.Plugins.JavScraper#126]
RT
![Screenshot 2021-02-21 at 9 12 02 PM](https://user-images.githubusercontent.com/5194603/108626124-88d60100-7489-11eb-9f5e-b3b49fb1274a.jpg)

刮削到的图片地址是：http://192.168.1.196:8096/emby/Items/RemoteSearch/Image?imageUrl=%2Femby%2FPlugins%2FJavScraper%2FImage%3Furl%3Dhttps%3A%2F%2Fpics.javbus.com%2Fthumb%2F77qu.jpg&ProviderName=JavScraper

访问的话，server会报 
Could not resolve type with token 0100006d from typeref (expected class 'System.ReadOnlySpan`1' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=************')

**Comment by feying-github** [comment]
个别还是普遍？试试你的nas能不能正常访问 https://pics.javbus.com/thumb/77qu.jpg

**Comment by kasimok** [comment]
> 个别还是普遍？试试你的nas能不能正常访问 https://pics.javbus.com/thumb/77qu.jpg

普遍的，几乎刷不出几张图片。插件没有挂任何代理(之前用socks5代理也是一样)，nas前面是一个merlin（KX上网）的路由器，浏览器和nas的ssh下用curl都能访问该图片，但是使用访问“http://192.168.1.196:8096/emby/Items/RemoteSearch/Image?imageUrl=%2Femby%2FPlugins%2FJavScraper%2FImage%3Furl%3Dhttps%3A%2F%2Fpics.javbus.com%2Fthumb%2F77qu.jpg&ProviderName=JavScraper”就是不行

**Comment by Mihu1314** [comment]
老哥咱俩问题一模一样 你解决了吗

**Comment by kasimok** [comment]
> 老哥咱俩问题一模一样 你解决了吗

还没解决，等作者修复呀

**Comment by Mihu1314** [comment]
我这解决了老哥 把emby升级到最新版4.5.4就可以了👀

发自我的iPhone

**Comment by kasimok** [comment]
> 我这解决了老哥 把emby升级到最新版4.5.4就可以了👀 发自我的iPhone
> […](#)
> 在 2021年3月16日，下午2:15，kakaiikaka ***@***.***> 写道： ﻿ 老哥咱俩问题一模一样 你解决了吗 还没解决，等作者修复呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

666我是装在群晖上的最新的才是4.4.3.0-1

**Comment by Mihu1314** [comment]
上emby官网 有针对群晖的最新版本 下载下来在群晖里手动更新一下

**Comment by kasimok** [comment]
> 上emby官网 有针对群晖的最新版本 下载下来在群晖里手动更新一下
> […](#)
> 在 2021年3月16日，下午7:52，kakaiikaka ***@***.***> 写道： ﻿ 我这解决了老哥 把emby升级到最新版4.5.4就可以了👀 发自我的iPhone … 在 2021年3月16日，下午2:15，kakaiikaka @.***> 写道： ﻿ 老哥咱俩问题一模一样 你解决了吗 还没解决，等作者修复呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 666我是装在群晖上的最新的才是4.4.3.0-1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks Bro! Works like a charm

**Comment by kasimok** [comment]
Close this as Synology users needs to use latest Emby.
