### ISSUE TITLE
请教下Docker如何安装以及是否支持分集？

### ISSUE THREAD

**Issue by tyhunter** [JavScraper/Emby.Plugins.JavScraper#15]
首先感谢作者开发了这个好用的插件~
想请教下，在DSM套件版本的emby运行成功了，但是不知道docker版本的，插件应该放在哪儿文件夹？
以及是否支持CD1\CD2\CD3这类的分集归类到一个影片下面，之前用AV_Data_Capture (https://github.com/yoshiko2/AV_Data_Capture) 这个本地刮削器是支持了这样的分集，在emby里CD1后面的部分会以附加内容的形式展示，不知道作者能否支持下？
再次感谢开发， 辛苦了！

**Comment by JavScraper** [comment]
docker 部署的话，你要使用泪水 `docker exec -it emby /bin/bash` 命令登录进去，找到插件目录，把插件目录映射出来或者把文件拷贝到插件目录。

分集功能，插件是无法支持的。只能在采集完成后，手动修改 文件名和nfo文件 来达成。

**Comment by tyhunter** [comment]
感谢成功了，另外需要docker exec -it emby /bin/sh 才能登陆进去，然后直接拷贝插件到config/plugins目录就可以了

分集这个功能看来还是得手动操作了，或者把分集摘出来用ADC先刮削好
