### ISSUE TITLE
建议增加排除功能，某些名字的视频不搜刮。

### ISSUE THREAD

**Issue by PHCSJC** [JavScraper/Emby.Plugins.JavScraper#19]
有些视频下载时总会带一个小视频，比如UUE29.mp4，搜刮器也会对这个视频进行搜刮，造成的后果是比较混乱，能否加一个排除选项，输入上面的名字后就忽略这些视频了。
谢谢！

**Comment by PHCSJC** [comment]
再一个小建议，代理可以设置socks5，我本地有个sock5，是过墙的，如果能直接支持sock5代理就更好了，感谢！

**Comment by tyhunter** [comment]
SHT的资源吧，这个直接在本地搜索删掉就好了，留着还占用空间。。。。

**Comment by feelingfrance** [comment]
配合everything,删除这些垃圾视频

**Comment by PHCSJC** [comment]
ok, thanks!
