### ISSUE TITLE
版本v1.2021.0603.0740封面裁剪不生效

### ISSUE THREAD

**Issue by zhuweitung** [JavScraper/Emby.Plugins.JavScraper#193]
emby v4.6.2.0
JavScraper v1.2021.0603.0740
无论是手动识别还是手动属性元数据都没有调用百度人体分析接口

**Comment by fallenyy** [comment]
> emby v4.6.2.0
> JavScraper v1.2021.0603.0740
> 无论是手动识别还是手动属性元数据都没有调用百度人体分析接口

请问存放女友头像的路径在哪里

**Comment by zhuweitung** [comment]
> > emby v4.6.2.0
> > JavScraper v1.2021.0603.0740
> > 无论是手动识别还是手动属性元数据都没有调用百度人体分析接口
> 
> 请问存放女友头像的路径在哪里

这个和我的问题不相关吧，女友头像路径我也没设置过
