### ISSUE TITLE
加载超级慢~约20s

### ISSUE THREAD

**Issue by Hoshigamifd** [JavScraper/Emby.Plugins.JavScraper#20]
我用的是win10 jellyfin 
点击演员头像查看这演员有多少电影时加载变的超级慢~~

从影片类别查看分类电影加载的就很快   不知道是jellyfin 还是插件的缘故

**Comment by JavScraper** [comment]
这个貌似不是插件的问题，emby也很慢。该插件只在刮削影片信息的时候工作。

**Comment by Hoshigamifd** [comment]
谢谢回复，这个我挂代理就正常了 -.-！
