### ISSUE TITLE
百度人体分析接口一直qps超限额

### ISSUE THREAD

**Issue by HEYANG1995** [JavScraper/Emby.Plugins.JavScraper#206]
百度人体分析接口是不是并发数设高了，免费只有2Qps,能不能设置这个值
![Screenshot_20210702-090130_Via](https://user-images.githubusercontent.com/16134777/124205583-1ef2f580-db14-11eb-89b6-b256b4941434.png)

**Comment by QZQ-QSQ** [comment]
请问免费时长用完后，是不是就要付费了？
