### ISSUE TITLE
请问执行采集缺失的女友头像后文件保存在哪里？

### ISSUE THREAD

**Issue by fallenyy** [JavScraper/Emby.Plugins.JavScraper#217]
计划任务种头像获取完毕，威联通套件版jellyfin无法显示头像，我改过jellyfin的媒体资料路径，不知是否有关系。大概下载了30G的数据但不知道存在哪里，我想手动转移出来。请告知文件储存路径。

**Comment by 4488dsq** [comment]
jellyfin/metadata/People
