### ISSUE TITLE
群晖7.0复制文件过去之后不显示菜单

### ISSUE THREAD

**Issue by wanghuisenior** [JavScraper/Emby.Plugins.JavScraper#253]
通过find命令查找plugins只能找到这三个目录可能与emby有关
/volume1/@appstore/EmbyServer/system/dashboard-ui/plugins
/volume1/@appstore/EmbyServer/system/plugins
/volume1/@appdata/EmbyServer/plugins
把dll文件复制到这三个目录，重启embyserver不显示菜单，用的是群晖7.0 emby4.6.4
哪位大佬知道怎么回事吗

**Comment by bjzhili** [comment]
同样的情况包括/var/packages/EmbyServer/target/system/plugins文件夹
                          /volume3/@appdata/EmbyServer/plugins
