### ISSUE TITLE
刮削器顺序调整后，重启emby又恢复默认了

### ISSUE THREAD

**Issue by PHCSJC** [JavScraper/Emby.Plugins.JavScraper#26]
javscraper版本：v1.22.146.1350
Emby版本：v4.3.1.0

刮削器顺序调整后，重启emby又恢复默认了。

大佬需要啥日志吗？

**Comment by JavScraper** [comment]
谢谢反馈，我这边能重现，我晚上更新下。

**Comment by JavScraper** [comment]
已经解决。

**Comment by PHCSJC** [comment]
还有一个问题：
重现方法，把JavBus调整到第一，保存，然后再调整JavDB到第一，再保存，发现保存不成功。
