### ISSUE TITLE
建议增加plex插件

### ISSUE THREAD

**Issue by PHCSJC** [JavScraper/Emby.Plugins.JavScraper#3]
非常感谢大佬分享这么好的插件，这是我用过的最好的jav scraper，已经在Emby上用了，显示效果实在是太赞了。

另外还有一款和Emby同样出名的软件Plex我也有在用，希望大佬也能把插件迁移到Plex。

谢谢！

**Comment by PHCSJC** [comment]
说下我主用Plex的原因，Emby的外网访问只能是http或https形式，现在的家宽管的越来越严，如果经常上v2ex的会知道，用http或https访问家宽很有可能被运营商判断为滥用而封掉宽带，所以我主要还是用Plex，安全性，淘宝上也只要300多块钱，所以希望大佬能把这个插件迁移到Plex上。

**Comment by JavScraper** [comment]
@PHCSJC 
- 其实你可以在家架设个 openvpn 服务器（udp 通行方式），先拨号再使用。
- Plex 也是通过 http 方式访问的，只是他自动映射端口，你没怎么感觉到而已。
- 有一种曲线的方式：Emby 保存信息到 NFO 中，Plex 安装 [XBMC nfo Movies Importer](https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle) 插件读取 nfo 文件。不过有点不完整。
- 还没搞过 Plex 的开发，看样子要用python，这个搞起来有点麻烦。

**Comment by PHCSJC** [comment]
感谢回复
1.我是在家建了个ss服务端，可以直接连到家里再开emby，避免了http暴露在公网。
2.原来plex也是http
3.保存到NFO，我把“媒体资料储存方式NFO”和”将媒体图像保存到媒体所在文件夹“都勾上了，但是并没有生成啊，好奇怪，问题出在哪呢？
4.看大佬兴趣，我可以帮测试。

**Comment by JavScraper** [comment]
没有生成 nfo 文件，可能是
- 文件夹权限问题？试着删除个文件看看。
- 需要新增的影片才会保存？试着弄个视频文件进去看看。或者刷新下某部电影的元数据。

**Comment by PHCSJC** [comment]
果然是权限的问题，Plex也可以读到nfo了，完美！大佬厉害。

**Comment by PHCSJC** [comment]
大佬有遇到这个问题吗？有3个文件：
ipx-443-C-.mp4
ipx-443-C-poster.png
ipx-443-C-fanart.png

Plex用XBMC nfo Movies Importer，fanart可以显示，但poster不显示，如果把ipx-443-C-poster.png文件名修改为poster.png就可以显示，大佬知道这个什么原因呢？

**Comment by JavScraper** [comment]
建议每个视频放到一个包含番号的单独文件夹中，感觉是 XBMC nfo Movies Importer 识别的问题。

**Comment by PHCSJC** [comment]
好像确实是XBMC nfo Movies Importer的识别问题，如果一个文件夹里只有一个视频，生成的文件就是poster.png和fanart.png，这是可以识别的。

看来只能这样了，感谢！
