### ISSUE TITLE
大佬不更新了吗

### ISSUE THREAD

**Issue by xiaoluan12** [JavScraper/Emby.Plugins.JavScraper#363]
emby上还有没有其他的刮削器可用啊

**Comment by 277383761** [comment]
有,但是必须用新版emby
https://github.com/metatube-community/jellyfin-plugin-metatube/releases

**Comment by xiaoluan12** [comment]
> 有，但必须用新版emby https://github.com/metatube-community/jellyfin-plugin-metatube/releases

谢谢，一直都是用的最新版emby
