### ISSUE TITLE
请问刮削器之前的默认顺序是什么呢？

### ISSUE THREAD

**Issue by PHCSJC** [JavScraper/Emby.Plugins.JavScraper#37]
刮削器网站的顺序被我调乱了，感觉刮出来的图片不怎么样。
请问在可以调整刮削器顺序之前的默认顺序是什么呢？谢谢！

**Comment by JavScraper** [comment]
之前顺序是代码编译的时候生成的，没啥意义。

建议你打开nfo文件看看，里面标明有数据来源于哪个采集器，把相应的采集器顺序调低就好。

比如：
```xml
  <javscraper-jsonid>{"Provider":"JavBus", ...}</javscraper-jsonid>
```
这里面的 **JavBus** 就是。

**Comment by PHCSJC** [comment]
好的，谢谢！
