### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by MYC3** [JavScraper/Emby.Plugins.JavScraper#4]
1. 希望能获取到类别标签、导演、系列、时间长度、制作商等等，当然越全越好
2.希望识别后得到的页面能把获取到的信息展示出来，并能删减编辑后导入

谢谢

**Comment by JavScraper** [comment]
- 你提到的这几项信息我都尝试获取了，但有各个网站上的信息并不是很全。
  - 针对影片时长，Emby 会自动生成的。
- Emby 的搜索结果界面只能展示那点信息，无法更改。
- Emby 本身支持编辑影片相关信息的。

谢谢反馈。
