### ISSUE TITLE
embyserver.txt 产生大量 Emby.Plugins.JavScraper.JavPersonTask: XXX not found

### ISSUE THREAD

**Issue by cecaa1030** [JavScraper/Emby.Plugins.JavScraper#40]
今天突然发现扫描新库的速度变慢了，去log查看发现大量 Emby.Plugins.JavScraper.JavPersonTask 日志，猜测是不是导入新媒体是每次都会自动尝试下载头像。如果是这样，这个功能可以做一个开关设置吗？否则导入大量媒体是速度明显被拖慢了

**Comment by cecaa1030** [comment]
卸载JavScraper后扫描速度恢复了，所以应该是和JavScraper有关

**Comment by JavScraper** [comment]
你emby中的女优可能之前没有头像，有新的女优会尝试获取头像，有些头像还蛮大的，会影响采集速度。建议在计划任务中先执行一遍采集。

**Comment by cecaa1030** [comment]
关键是我导入的根本不是JAV啊，就是普通的Movie和Tv，这个时候不需要JavScraper帮我尝试获取头像吧，是不是在Meta搜刮器选中JavScraper的时候才尝试获取头像会比较好？现在是不选中JavScraper的时候也会自动尝试获取头像

**Comment by JavScraper** [comment]
这个问题。。。因为演员信息是全局的，没法单独对某个媒体库设置开关。

不过不用担心网络请求问题，那个演员列表1个小时刷新一次。一个小时内是用缓存的数据，也就是在本地查找是否有头像，并不会发起网络请求。

就是日志多了点。

**Comment by cecaa1030** [comment]
现在我卸载了JavScraper之后导入速度快了很多很多，所以这个差别还真是很大的。那能不能做一个这个功能的开关，让我们可以自己决定什么时候开启头像获取功能呢？感谢

**Comment by cecaa1030** [comment]
哥们，加个开关呗？我现在都不敢装插件，辛苦啦~

**Comment by cecaa1030** [comment]
我看了下JavPersonTask.cs的代码，因为实现了ILibraryPostScanTask，所以任何扫描库的操作后都会执行这个Task，在这个Task中每次执行都会对整个Emby头像库没有头像的演员挨个使用Gfriends尝试获取头像。这在Emby库很大的情况下，我可能扫描库的动作只要几秒钟，但是这个JavPersonTask就要执行几十分钟。对于我来说，有IScheduledTask定期扫描头像就已经够了，完全不需要每次扫描任何库之后就来一个整体Emby头像库扫描，这样效率太低了。

**Comment by cecaa1030** [comment]
标题和实际问题不符合，我关掉新开一个issue
