### ISSUE TITLE
百度翻译无法使用

### ISSUE THREAD

**Issue by lyklll** [JavScraper/Emby.Plugins.JavScraper#48]
当前版本是 v1.22.178.811

![image](https://user-images.githubusercontent.com/31095757/86473706-01aa1080-bd74-11ea-8e60-6f140102f914.png)

选了也保存不成功

**Comment by cnfniw** [comment]
是的，没法使用。保存不成功。

**Comment by lyklll** [comment]
> 是的，没法使用。保存不成功。

上个版本都可以的~

**Comment by JavScraper** [comment]
@lyklll @cnfniw @xinxin8816 新版本已经支持Jellyfin的样式。
