### ISSUE TITLE
Jellyfin 版本百度人体识别选项不能勾上

### ISSUE THREAD

**Issue by muihiuwev** [JavScraper/Emby.Plugins.JavScraper#50]
如题，勾上后保存，刷新页面后仍然是未勾上。

**Comment by fmbfmbhh** [comment]
我的人本识别根本就没有调用，不知道为何

**Comment by 66508393** [comment]
我在vps的jellyfin怎样安装这个插件的？？

**Comment by oweaF** [comment]
![image](https://user-images.githubusercontent.com/25154231/89091429-44472300-d3dc-11ea-9362-bc683ce5f48b.png)

jellyfin里的设置页面UI有问题，勾选后没办法正常的显示输入框

![image](https://user-images.githubusercontent.com/25154231/89091496-c8010f80-d3dc-11ea-9680-5e4c91431b68.png)

但是在网页开发工具元素审核里面是能看到相关的元素的。

**Comment by zhaihaichuan** [comment]
> ![image](https://user-images.githubusercontent.com/25154231/89091429-44472300-d3dc-11ea-9362-bc683ce5f48b.png)
> 
> jellyfin里的设置页面UI有问题，勾选后没办法正常的显示输入框
> 
> ![image](https://user-images.githubusercontent.com/25154231/89091496-c8010f80-d3dc-11ea-9680-5e4c91431b68.png)
> 
> 但是在网页开发工具元素审核里面是能看到相关的元素的。

同样问题，希望作者更新适配

**Comment by oweaF** [comment]
Jellyfin\Server\plugins\configurations\JavScraper.xml
可以直接修改这个配置文件，也能用

**Comment by Mrcoolfuyu** [comment]
同样问题，希望作者更新适配

**Comment by JavScraper** [comment]
@muihiuwev @oweaF @Mrcoolfuyu @66508393 @fmbfmbhh 新版本已经支持Jellyfin的样式
