### ISSUE TITLE
jellyfin安装后无法配置

### ISSUE THREAD

**Issue by xueshao** [JavScraper/Emby.Plugins.JavScraper#53]
![image](https://user-images.githubusercontent.com/20736038/89098522-0f0df580-d41b-11ea-891c-08516e43a4cf.png)
如上图所示 配置菜单看不到

jellyfin版本10.6.1

求助!

**Comment by JavScraper** [comment]
可能是样式不兼容，我下载个版本看看。

**Comment by xueshao** [comment]
好的,感谢作者付出

**Comment by JavScraper** [comment]
可能是css样式有问题。晚点我下个新版本测试下。

**Comment by wangzhiyong2019** [comment]
docker里的jellyfin，这个插件怎么安装？

**Comment by 1458271** [comment]
jellyfin版本 10.6.3
问题同上，感觉应该是样式出了问题，可能是emby的css和jeffyfin不兼容？

**Comment by JavScraper** [comment]
@xueshao @1458271 @xinxin8816 新版本已经兼容jeffyfin的样式。
