### ISSUE TITLE
有些素人番号还是搜刮不出来

### ISSUE THREAD

**Issue by linguowei** [JavScraper/Emby.Plugins.JavScraper#6]
首先感谢作者，这个插件很好用，但还是有些番号搜刮不出来，比如 300MAAN-244，261ARA-391，300NTK-038这样的，是我的哪里配置问题吗

**Comment by JavScraper** [comment]
不是你的配置问题，可能是采集的那几个网站没有。

你是否知道还有其他网站可以采集以上的番号的？

**Comment by linguowei** [comment]
@JavScraper 你列出来的采集源中 **MsgTage** 这个站点是可以搜到我发出来的那几个番号的，不知道是没有适配这个站点的原因吗？

**Comment by JavScraper** [comment]
@linguowei 我刚才试了下，JavScraper 可以采集到 `300MAAN-244`，可能原因是命名不规范，或者 改文件所在的文件夹没有包含这个番号。你可以手动尝试搜索看看。

**Comment by linguowei** [comment]
@JavScraper 应该不是命名的原因，我的文件名只有番号，没其它内容了，应该是忽略大小写的吧，我试了手动还是搜刮不出来，难道是我代理的原因吗？或者说有什么办法检查我配置的JsProxy是正常的？

**Comment by JavScraper** [comment]
@linguowei 有两个方式可以检查
1, https://xxx.xxxx.workers.dev/http/http/https://www.google.com  打开有内容则工作正常。
2, 检查 Emby 的错误日志。

**Comment by linguowei** [comment]
@JavScraper 有内容，代理应该是正常的，因为fc2之类的是可以搜刮的，正常非素人番号的也都没问题，这就奇怪了，为啥你能采集到我这边不行

**Comment by JavScraper** [comment]
选择影片手动识别看看。

**Comment by linguowei** [comment]
@JavScraper 感谢你的耐心回答，手动识别我也试过了，如果你那边能搜刮到，那应该是我的网络问题吧，我再慢慢找找原因了

**Comment by JavScraper** [comment]
@linguowei 话说，你有没用更新配置里面的素人番号列表里，增加或者移除300MAAN看看?

**Comment by linguowei** [comment]
@JavScraper 刚刚测试了一下，还是不行呢，素人番号我这边只有fc2之类的可以搜刮出来，非素人，ssni-xxx，abp-xxx 之类的都没问题

**Comment by linguowei** [comment]
@JavScraper 素人的信息看看是否可以适配一下这个网站的，我看数据挺全的 [https://www.jav321.com](https://www.jav321.com)

**Comment by JavScraper** [comment]
这个网站已经加上了的，我感觉应该是配置的问题。
你尝试在**素人番号**中加减**MAAN**关键字试试看。

**Comment by linguowei** [comment]
@JavScraper 可以了，300MAAN-244这个我发现去掉300 ，MAAN-244这样就能搜索到

**Comment by linguowei** [comment]
@JavScraper 但是261ARA-391这个我就怎么都搜不到了，jav321这个站点是有数据的

**Comment by linguowei** [comment]
@JavScraper 你好，再冒昧请教一下，采集配置那里的逻辑我有点弄不明白，举例300MAAN-244，261ARA-391这两个，我发现需要在采集配置那里移除掉MAAN，ARA这个两个关键字，然后手动识别的时候也不能带上番号的数字前缀，这样MAAN-244，ARA-391才能搜刮到数据

**Comment by JavScraper** [comment]
在番号列表中的番号只从MgsTage抓取。。。下个版本更新感觉可以取消掉。你可以看下日志，有时候可能解析番号不正确。

**Comment by JavScraper** [comment]
已经去除素人选项了。。。

**Comment by linguowei** [comment]
@JavScraper 刚刚升级测试了，不错，点赞👍

**Comment by KeshuidaW** [comment]
> 首先感谢作者，这个插件很好用，但还是有些番号搜刮不出来，比如 300MAAN-244，261ARA-391，300NTK-038这样的，是我的哪里配置问题吗

额，300maan244是富田优衣，另外的她还有300maan284还是274来着 ， 还有不300mium多少的记不清了。再就是一些正常番号，工作机器啊，其他那些不太好看，就300maan244好点

**Comment by ZXCASD854** [comment]
[>>>>手机看片你懂的](http://618sss.com)

[>>>>手机看片你懂的](http://618sss.com)

[>>>>手机看片你懂的](http://618sss.com)

[>>>>手机看片你懂的](http://618sss.com)

[>>>>手机看片你懂的](http://618sss.com)

**Comment by heiliaoKTV** [comment]
51吃瓜黑料网-17吃瓜· 今日吃瓜· 吃瓜榜单· 热门大瓜· 必看大瓜-网络热门事件吃瓜网
------------------------
发布页>>><a href="https://heiliaoktv.github.io/chigua.github.io/">👉点击进入👈</a><<<【更新时间：2024年8月6日】
------------------------
【热门大瓜】17吃瓜网乱伦大瓜【天津二舅】网传天津南开泄密真实乱伦大瓜 外甥女和二舅爸爸车震乱伦1分11秒视频泄密流出，外甥女被操得疯狂喊叫：二舅爸爸，爸爸操我！！

【麻豆传媒】16岁麻豆女神潘甜甜出道即巅峰三部曲《手机的秘密》《少女的悔悟》《七夕牛郎织女》

【麻豆传媒】台湾第一暗黑女网红吴梦梦从网红到暗黑界的蜕变：在华语暗黑界，吴梦梦或许不算最漂亮的女生，但她却在海外知名度方面独树一帜。

祝贺【日本AV女优】波多野结衣、天海翼、吉沢明步(吉泽明步)、早川濑里奈、大桥未久、美竹凉子、松岛枫、佐佐木希、上原结衣、朝美穗香、千田理子(爱川美里菜)、纹舞兰、水菜丽、加藤莉娜、樱井莉亚、椎名由奈、卯月麻衣、樱理惠、横山美雪、伊泽千夏等女优成功入驻17吃瓜网！！

祝贺【麻豆传媒女神全集】叶一涵、叶倩茹、吴梦梦、唐心、夏晴子、宁洋子、安娜、尹媚、徐韵姗、沈娜娜、艾秋、秦可欣、董小宛、林予曦、王茜、欧美玲、杜冰若、李慕儿、刘思慧、刘语姗、欧阳晶、林思妤、李婧琪、赵颖儿、罗锦宣、雪千夏、夏莹、郭童童、许月珍、张芸熙、赵佳美、许安妮等女优成功入驻17吃瓜网！！

17吃瓜，全网更新最快，瓜料最全，千万吃瓜群众信赖的吃瓜网站！ 一起来吃瓜吧！明星黑料、网红大瓜、热搜大瓜、海外大瓜、热门热榜、校园情侣、自拍更拍！！

**Comment by justhyj** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
晕倬使固淮靥不首辣缓紫傻
