### ISSUE TITLE
debian9 配置的jellyfin不能调设置啊

### ISSUE THREAD

**Issue by NiuXZi** [JavScraper/Emby.Plugins.JavScraper#61]
![image](https://user-images.githubusercontent.com/61132813/89727614-10fa3900-da59-11ea-94ee-77fcfb14a23f.png)
这个地方就算点了，刷新一下就没了，和给出的示例差距很大，是不适配吗？

**Comment by extranquil** [comment]
+1
还木有解决吗

**Comment by bladesz123** [comment]
+1, 10.55版本Jellyfin+白群晖，无法设置

**Comment by NiuXZi** [comment]
> +1
> 还木有解决吗

我后来换emby了，发现可以用。。。

**Comment by bladesz123** [comment]
我也是专门换了emby，等作者更新吧

________________________________
发件人: NiuZXi <notifications@github.com>
发送时间: 2020年11月17日 15:34
收件人: JavScraper/Emby.Plugins.JavScraper <Emby.Plugins.JavScraper@noreply.github.com>
抄送: bladesz123 <yz850@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [JavScraper/Emby.Plugins.JavScraper] debian9 配置的jellyfin不能调设置啊 (#61)


+1
还木有解决吗

我后来换emby了，发现可以用。。。

―

**Comment by JavScraper** [comment]
@chanh0 @extranquil @NiuXZi @bladesz123 新版本已经适配Jellyfin的样式。

**Comment by bladesz123** [comment]
> @chanh0 @extranquil @NiuXZi @bladesz123 新版本已经适配Jellyfin的样式。

多谢
