### ISSUE TITLE
小白想问一下，怎么在群晖里ssh到emby的文件夹

### ISSUE THREAD

**Issue by bccu1986** [JavScraper/Emby.Plugins.JavScraper#7]
真是小白，这一步不太会，望指教

**Comment by bccu1986** [comment]
> 真是小白，这一步不太会，望指教

**Comment by JavScraper** [comment]
@bccu1986 官网帮助文档有说： [如何通过 SSH/Telnet 用 root 权限登录 DSM](https://www.synology.com/zh-cn/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet)
