### ISSUE TITLE
部分系列的cover/poster分辨率低

### ISSUE THREAD

**Issue by Jue-Xu** [JavScraper/Emby.Plugins.JavScraper#87]
部分abp（比如abp949，abp994）的cover来源是jav321 而不是 pics.dmm.co.jp，导致图片分辨率低。手动在jav321上搜这部片子，封面来源是pics.dmm.co.jp。

比如：目前nfo中封面来源是
`"Cover":"https://www.jav321.com/images/prestige/abp/994/pf_o1_abp-994.jpg"`
但是希望的高清封面应该是
`https://pics.dmm.co.jp//digital/video/118abp00994/118abp00994pl.jpg`

**Comment by Jue-Xu** [comment]
解决了，办法是：把abp949.mp4放到abp949文件夹里（之前把所有片子都放在一个文件夹里），然后扫描一次就得到高清的封面。很奇怪的是：这样做以后，abp949文件夹里没有nfo和图片文件，不知道那种管理文件的方式比较推荐

**Comment by JavScraper** [comment]
emby 优先使用文件夹名称作为影片的标题。如果有多个视频文件，才会用文件名作为标题。

可以调整采集器的顺序的。
