### ISSUE TITLE
希望修复javdb刮削器

### ISSUE THREAD

**Issue by sayasacglife** [JavScraper/Emby.Plugins.JavScraper#89]
使用Jellyfin10.6.4，JavScraper v1.2020.1214.2259
javdb刮削器目前不可用，例如zex-145不能识别，手动识别结果为空

**Comment by jakzhi104** [comment]
Emby也有這個問題，v1.2020.1214.2259。昨天還正常，今天就不可用了。

**Comment by jakzhi104** [comment]
應該是代理問題。我這邊取消代理就正常使用了，我是在牆外。

**Comment by sayasacglife** [comment]
墙内，浏览器挂代理能正常打开javdb，插件挂的本地代理

**Comment by smilejoker365** [comment]
我也出现这个问题了，我估计是cloudflare代理的问题，但是我把刮削网站换成免翻网址，也还是不行。下午还能用，晚上突然不行了

**Comment by sayasacglife** [comment]
也许是代理问题？
参照其他人的代码注释X-FORWARDED-FOR后能正常获取搜索结果，但是新问题是不能保存图像。。
`protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            // request.Headers.TryAddWithoutValidation("X-FORWARDED-FOR", "17.172.224.88");`

**Comment by CoolByte1024** [comment]
我目前存在的问题是，首次刮削可以，但是之后图像不能保存

**Comment by JavScraper** [comment]
试下新版本看看。
