### ISSUE TITLE
媒体库重新刮削的问题

### ISSUE THREAD

**Issue by MccYcore** [JavScraper/Emby.Plugins.JavScraper#93]
发现用javbus不能刮削出简介信息，现在打算将整个媒体库重新用jav321刮削，但是修改javscraper设置后直接刷新元数据，刮削器还是会默认使用javbus，显然是在初次刮削的时候为每一部电影执行了某种默认设置。请问如何更改这个设置

**Comment by JavScraper** [comment]
试下新版本看看。
